FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir 'waitress==3.0.2'
COPY wsgi_app.py /app/wsgi_app.py
COPY run_waitress_prof.py /app/run_waitress_prof.py
EXPOSE 8000
CMD ["python", "/app/run_waitress_prof.py"]
