ServerRoot "/usr/local/apache2"
Listen 8000
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule lua_module modules/mod_lua.so

User daemon
Group daemon
ServerName localhost:8000
DocumentRoot "/usr/local/apache2/htdocs"
ErrorLog /dev/stderr
LogLevel warn
TypesConfig /usr/local/apache2/conf/mime.types

<Directory />
    AllowOverride None
    Require all granted
</Directory>

LuaMapHandler /health /usr/local/apache2/htdocs/health.lua handle
LuaMapHandler /upload /usr/local/apache2/htdocs/upload.lua handle
