FROM ruby:3.3-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN gem install --no-document unicorn:6.1.0 rack:3.1.7 stackprof:0.2.27
COPY config.ru /app/config.ru
COPY unicorn.conf.rb /app/unicorn.conf.rb
EXPOSE 8000
CMD ["unicorn", "-c", "/app/unicorn.conf.rb", "/app/config.ru"]
