"""Render the master comparison matrix table.

Output:
  - results/matrix.md   (Markdown table; consumable by humans)
  - figures/matrix_table.tex (LaTeX tabularx-compatible; consumable by paper)
  - data/all.json (concat of wave1 + wave2)

Run:
  uv run python projects/asgi-perchunk-survey/scripts/render_matrix.py
"""
from __future__ import annotations
import json
import pathlib

from _common import load_all_servers, server_label, measurement, PROJECT_DIR


RESULTS = PROJECT_DIR / "results"
FIGS    = PROJECT_DIR / "figures"
DATA    = PROJECT_DIR / "data"


def best_us_per_chunk(s: dict) -> float | None:
    """Mode B paced at N=250K is the canonical comparator;
    fall back to Mode A at 250K, else any later measurement."""
    candidates = [
        ("B-paced-100us", 250_000),
        ("B-paced-100us", 100_000),
        ("A-bridge-coalesced", 250_000),
        ("A-bridge-coalesced", 1_000_000),
    ]
    for mode, n in candidates:
        m = measurement(s, mode, n)
        if m and m.get("server_us_per_chunk"):
            return m["server_us_per_chunk"]
    # last resort: scan all
    for m in s.get("measurements", []):
        if m.get("server_us_per_chunk"):
            return m["server_us_per_chunk"]
    return None


def worst_wall(s: dict) -> tuple[int | None, float | None]:
    """Slowest wall-time cell across all measurements."""
    worst = None
    for m in s.get("measurements", []):
        if m.get("wall_seconds") is not None:
            if worst is None or m["wall_seconds"] > worst[1]:
                worst = (m.get("n_bytes"), m["wall_seconds"])
    return worst if worst else (None, None)


VERDICT_ORDER = {
    "BATCHES-CORRECTLY":         0,
    "VULNERABLE-PER-RECV-ONLY":  1,
    "VULNERABLE-PER-CHUNK":      2,
    "QUADRATIC":                 3,
    "CRASHES":                   4,
    "UNKNOWN":                   5,
}


def main():
    RESULTS.mkdir(parents=True, exist_ok=True)
    FIGS.mkdir(parents=True, exist_ok=True)

    all_servers = load_all_servers()
    # Save concatenated JSON for downstream tooling
    (DATA / "all.json").write_text(json.dumps({"servers": all_servers}, indent=2))

    # The main matrix is HTTP/1-only: a server qualifies if it has at least
    # one A-bridge-coalesced or B-paced-100us measurement.
    HTTP1_MODES = {"A-bridge-coalesced", "B-paced-100us", "control-single-write",
                   "CONTROL-content-length"}

    def has_http1(s):
        return any(m.get("mode") in HTTP1_MODES for m in s.get("measurements", []))

    servers = [s for s in all_servers if has_http1(s)]
    wave3_only = [s for s in all_servers if not has_http1(s)]

    # Sort by verdict then by us/chunk ascending
    servers.sort(key=lambda s: (
        VERDICT_ORDER.get(s.get("verdict", "UNKNOWN"), 9),
        best_us_per_chunk(s) or 9e9,
    ))

    # ---- Markdown matrix ----
    lines = [
        "# Master comparison matrix",
        "",
        "Generated automatically from `data/wave*.json`. Re-render via",
        "`uv run python projects/asgi-perchunk-survey/scripts/render_matrix.py`.",
        "",
        "| # | Server | Version | Ecosystem | Concurrency | Parser | Verdict | µs/chunk | Worst wall | Scaling |",
        "|---|--------|---------|-----------|-------------|--------|---------|---------:|-----------:|---------|",
    ]
    for i, s in enumerate(servers, 1):
        upc = best_us_per_chunk(s)
        upc_str = f"{upc:g}" if upc else "—"
        n, w = worst_wall(s)
        worst_str = f"{w:g}s @ N={n:,}" if (w and n) else (f"{w:g}s" if w else "—")
        scaling = s.get("scaling_exponent_mode_a")
        scaling_str = f"{scaling:g}" if scaling else "—"
        lines.append(
            f"| {i} | {server_label(s)} "
            f"| {s.get('version','—')} "
            f"| {s['ecosystem']} "
            f"| {s.get('concurrency_model','—')} "
            f"| {s.get('parser','—')[:30]} "
            f"| **{s.get('verdict','UNKNOWN')}** "
            f"| {upc_str} "
            f"| {worst_str} "
            f"| {scaling_str} |"
        )

    # Verdict tally
    tally = {}
    for s in servers:
        tally[s["verdict"]] = tally.get(s["verdict"], 0) + 1
    lines += [
        "",
        f"**Total HTTP/1.1 servers measured: {len(servers)}**",
        f"(+{len(wave3_only)} additional servers in Wave 3 HTTP/2 + WebSocket; see protocol-compare chart)",
        "",
        "## Verdict tally (HTTP/1.1)",
        "",
        "| verdict | count |",
        "|---------|------:|",
    ]
    for v in sorted(tally, key=lambda k: VERDICT_ORDER.get(k, 9)):
        lines.append(f"| {v} | {tally[v]} |")
    lines.append("")

    out_md = RESULTS / "matrix.md"
    out_md.write_text("\n".join(lines))
    print(f"wrote {out_md}")

    # ---- LaTeX tabularx for paper ----
    tex = [
        r"% auto-generated by scripts/render_matrix.py",
        r"\begin{tabularx}{\linewidth}{@{}r l l l l Xr@{}}",
        r"\toprule",
        r"\# & server & version & ecosystem & verdict & $\mu$s/chunk \\",
        r"\midrule",
    ]
    for i, s in enumerate(servers, 1):
        upc = best_us_per_chunk(s)
        upc_str = f"{upc:g}" if upc else "---"
        # LaTeX-escape underscores and ampersands in displayed strings
        def latex_esc(t: str) -> str:
            return (t.replace("\\", r"\textbackslash{}")
                     .replace("_", r"\_")
                     .replace("&", r"\&")
                     .replace("%", r"\%")
                     .replace("#", r"\#"))
        tex.append(
            f"{i} & {latex_esc(server_label(s))} & "
            f"{latex_esc(s.get('version','---'))} & "
            f"{latex_esc(s['ecosystem'])} & "
            f"\\texttt{{{latex_esc(s.get('verdict','UNKNOWN'))}}} & "
            f"{upc_str} \\\\"
        )
    tex += [r"\bottomrule", r"\end{tabularx}"]
    out_tex = FIGS / "matrix_table.tex"
    out_tex.write_text("\n".join(tex))
    print(f"wrote {out_tex}")


if __name__ == "__main__":
    main()
