FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY Kestrel.csproj .
COPY Program.cs .
RUN dotnet restore && dotnet publish -c Release -o /app /p:PublishTrimmed=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://0.0.0.0:8000
ENV DOTNET_EnableDiagnostics=1
EXPOSE 8000
ENTRYPOINT ["dotnet", "Kestrel.dll"]
