server.port=8000
server.address=0.0.0.0
spring.main.banner-mode=off
logging.level.root=WARN
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
spring.servlet.multipart.enabled=false
